version: '3'

services:
    dnsmasq:
        restart: always
        image: strm/dnsmasq
        network_mode: host
        deploy:
            replicas: 1        
        configs:
            - dnsmasq:/etc/dnsmasq.conf
        ports:
            - "53:53/udp"
        cap_add:
            - NET_ADMIN

      
configs:
    dnsmasq:
        file: ./dnsmasq.conf
