version: '3.6'

services:
  gDrive:
    image: mumiehub/rclone-mount
    environment:
      TZ: Europe/Madrid
      MountCommands: "--allow-other --allow-non-empty --dir-cache-time 48h --poll-interval 5m --buffer-size 128M"
      RemotePath: "mediaefs:"
      MountPoint: "/mnt/mediaefs"	
      UnmountCommands: "-u -z"	
    #volumes:
      #- /path/to/config:/config
      #- /host/mount/point:/mnt/mediaefs:shared
      #- /dev/fuse:/dev/fuse
    #config:
      #- /path/to/config:/config/.rclone.conf
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined

#volumes:
#  haproxy_data:
