version: '3.6'

services:
  jdownloader:
    image: jaymoulin/jdownloader
    environment:
      TZ: Europe/Madrid
    volumes:
      - jdownloader_downloads:/root/Downloads
      - jdownloader_config: /opt/JDownloader/cfg

volumes:
  jdownloader_downloads:
  jdownloader_config:
 
 
 # Access through jdownloader web api (config neeeded)
 # docker exec jdownloader configure email@email.com password 
 # https://my.jdownloader.org/index.html#dashboard
