version: '3.6'

# Multi ARCH-docker
# https://github.com/jaymoulin/docker-jdownloader 
## Access through jdownloader web api (config neeeded)
## docker exec jdownloader configure email@email.com password 
## https://my.jdownloader.org/index.html#dashboard
 
services:
  jdownloader:
    image: jaymoulin/jdownloader
    hostname: jdownloader.londres.casa
    #depends_on:
      #- disco
    environment:
      TZ: Europe/Madrid
    volumes:
      - jdownloader_downloads:/root/Downloads
      - jdownloader_config: /opt/JDownloader/cfg

volumes:
  jdownloader_downloads:
  jdownloader_config:
 
 
 
 
 ####
 docker volume create jdownloader

docker run -d \
    --restart=always \
    -v /storage/alcazar/torrent:/root/Downloads \
    -v jdownloader:/opt/JDownloader/cfg \
    --name jdownloader \
    -u $(id -u):$(id -g) \
    jaymoulin/jdownloader
    
    
        --label traefik.backend=transmission \
    --label traefik.port=9091 \
    --label traefik.frontend.rule="Host:transmission.londres.casa" \
    --label traefik.frontend.entryPoints=http \
