version: '3.3'

services:
  NodeRed:
    image: "nodered/node-red-docker"
    restart: always
    deploy:
      replicas: 1
    ports:
      - 1880:1880
    volumes:
      - "nodered_data:/openhab"

volumes:
  nodered_data:
  
version: '2'
services:
    nodered:
        build: build
        image: elzekool/rpi-nodered
        ports:
            - "1880:1880"
        volumes:
            - "${PWD}/data:/root/.node-red"
        privileged: true
        restart: "unless-stopped"


docker run -it -p 1880:1880 \
    --name nodered \
    --label traefik.backend=nodered \
    --label traefik.port=1880 \
    --label traefik.frontend.rule="Host:nodered.londres.casa" \
    --label traefik.frontend.entryPoints=http \
    elzekool/rpi-nodered
