version: '3.6'

services:
  OpenHab:
    image: "openhab/openhab:2.3.0-amd64-debian"
    restart: always
    deploy:
      replicas: 1
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "openhab_data:/openhab"
    command: "./start.sh server"

volumes:
  openhab_data:
