
version: "3.3"
services:
  rabbitmq:
    image: lovelysystems/rabbitmq-swarm-cluster
    #hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    hostname: "rabbitmq.londres.casa"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc
      - RABBITMQ_USE_LONGNAME=true
      - RABBITMQ_MNESIA_DIR=/var/lib/rabbitmq/mnesia
      - RABBITMQ_PLUGINS_EXPAND_DIR=/var/lib/rabbitmq/mnesia/plugins-expand
      - SERVICE_NAME={{.Service.Name}}
      - SLOT={{.Task.Slot}}
      - MASTER_SLOT=1
    ports:
      - "5672:5672"   # amqp
      - "15672:15672" # web ui
      
 # Funciona app portainer. La version normal de rabbit docker funciona en rpi
 
 docker run -d \
     --hostname mqtt.londres.casa \
     --name rabbitmq \
     -p 1883:1883 \
     -p 9001:9001 \
     --label traefik.backend=mqtt \
     --label traefik.port=15672 \
     --label traefik.frontend.rule="Host:mqtt.londres.casa" \
     --label traefik.frontend.entryPoints=http \
     rabbitmq:3-management
     
 
 
 docker run -ti --name mosquitto  -p 1883:1883 -p 9001:9001 pascaldevink/rpi-mosquitto 
