version: '3.6'

services:
  rclone:
    image: mumiehub/rclone-mount
    environment:
      TZ: Europe/Madrid
      MountCommands: "--allow-other --allow-non-empty --dir-cache-time 48h --poll-interval 5m --buffer-size 128M"
      RemotePath: "mediaefs:"
      MountPoint: "/mnt/mediaefs"	
      UnmountCommands: "-u -z"	
    #volumes:
      #- /path/to/config:/config
      #- /host/mount/point:/mnt/mediaefs:shared
      #- /dev/fuse:/dev/fuse
    #config:
      #- /path/to/config:/config/.rclone.conf
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined

#volumes:
#  haproxy_data:

--allow-other \
--read-only \
--default-permissions \
--uid 1000 \
--gid 1000 \
--umask 002 \
--acd-templink-threshold 0 \
--buffer-size 100M \
--timeout 5s \
--contimeout 5s \
--syslog \
--stats 1m \
-v \


docker run -d \
    --name rclone-mount \
    --restart=unless-stopped \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    -e RemotePath="alcazar:" \
    -e MountCommands="--allow-other --allow-non-empty" \
    -v rclone:/config \
    -v alcazar:/mnt/alcazar \
    mumiehub/rclone-mount
    
  --restart=always \
&& sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf \

docker run -it --rm=true \
  --name alcazar \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  --security-opt apparmor:unconfined \
  -v rclone:/home/pi/alcazar \
  -v /var/lib/docker/volumes/rclone.conf:/root/.rclone.conf \
  rclone \
  rclone mount alcazar: /home/pi/alcazar \
  --checkers 16 --dir-cache-time 30m -vv --allow-other --allow-non-empty --dir-cache-time 48h
  
  
  
  docker run -d \
  --name alcazar \
  --restart=always \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  --security-opt apparmor:unconfined \
  -v rclone:/data \
  -v /var/lib/docker/volumes/rclone.conf:/config/.rclone.conf \
  tynor88/rclone-mount:dev
  
  
  
  rclone mount alcazar: /home/pi/alcazar \
  --checkers 16 --dir-cache-time 30m -vv --allow-other --allow-non-empty --dir-cache-time 48h
  
  
  -----no funciona nada de lo anterior-------
nohup  rclone copy --fast-list -vvvv --size-only --transfers=2 --bwlimit=8M /media/almacen/torrent/ alcazar:/almacen/ &
